# Generated by Django 4.1.5 on 2024-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TotalLife_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('C', 'Cancelled'), ('D', 'Done')], default='S', max_length=10),
        ),
    ]
